import ownet
from time import localtime, mktime

ownet.init('localhost:4304')

sFilename = '/etc/owtg/sensors'
sFile = open(sFilename,'r') #discovered file, open for reading
dAddresses = [] #already discovered addresses
newAddresses = [] #new addresses found during this run
newFile = [] #array of lines to write out to file

newFile.append('#This is an automatically generated file\n')
newFile.append('#DO NOT edit this file by hand; it may cause undefined behaviour\n')
newFile.append('#[alias]:[address]:[timestamp]:[graph(y/n)]\n')

lineList = sFile.readlines()

sFile.close()

for line in lineList:
    #ignore comments (lines beginning with #)
    if line.startswith('#'):
        continue
    #append each line to the "new file" so as not to destroy the data
    newFile.append(line)
    if line:
        dAddresses.append(line.split(':')[1])

for directory in ownet.Sensor('/','localhost',4304).sensorList():
    seen = False
    address = None
    #exclude "simultaneous" as it has a temperature file but is not a sensor
    if directory == ownet.Sensor('/simultaneous','localhost',4304):
        continue

    #If the directory contains "temperature", it is a sensor
    if hasattr(directory,'temperature'):
        #store the address
        address = directory.address
        for a in dAddresses:
            #check against every discovered addresss
            if address == a:
                seen = True
                break
        #if the address has not been already discovered, add it to newAddresses
        if not seen:
            newAddresses.append(address)

for a in newAddresses:
    #Build a string in the form of "[alias(empty)]:[address]:[timestamp]:[graph(y/n)]\n"
    sensorLine = ':' + a + ':' + str(mktime(localtime())).split('.')[0] + ':n\n'
    #Append it to the new file line array
    newFile.append(sensorLine)

newFile.sort();
sFile = open(sFilename,'w') #sensors file, open for writing
sFile.writelines(newFile)
sFile.close()

